// The parking API as a Supabase Edge Function. server.js is generated by `npm run build:function`
// from server/edge.ts; deploy with `npx supabase functions deploy api --no-verify-jwt`.
import { handle } from "./server.js";

Deno.serve(handle);
